library(ncdf4)
nc <- nc_open("E:/Zhitao/From Zhitao/SSTS_GRDT_22-24/SSTS_GRDT_combined.nc")
print(nc)
nc_lon <- ncvar_get(nc, "lon")
nc_lat <- ncvar_get(nc, "lat")
cat("lon dim:", dim(nc_lon), "\n")
cat("lat dim:", dim(nc_lat), "\n")
cat("lon range:", range(nc_lon), "\n")
cat("lat range:", range(nc_lat), "\n")
slab <- ncvar_get(nc, "SSS", start=c(1,1,1), count=c(-1,-1,1))
cat("SSS slab dim:", dim(slab), "\n")
cat("SSS range:", range(slab, na.rm=TRUE), "\n")
nc_close(nc)
